### ISSUE TITLE
Documentar a API com swagger

### ISSUE THREAD

**Issue by lucashdp** [smart-campus-newton/me-empresta-api#4]
Swagger é um framework open-source gratuito utilizado pra arquitetar, construir, documentar e consumir APIs RESTful.

https://swagger.io/ 

Documentar os endpoints já existentes

**Comment by RonildoSouza** [comment]
No Guide Development sugerido no issue [#6](https://github.com/smart-campus-newton/me-empresta-api/issues/6#issuecomment-473341408) adicionar uma informação de como gerar está documentação.

**Comment by lucashdp** [comment]
Boa @RonildoSouza !
Eu já fiz uma documentação parecida:
https://github.com/lucashdp/catalog-microservice

**Comment by lucashdp** [comment]
Issue finalizada e a documentação está disponível em:
https://me-empresta.herokuapp.com/api-docs/
