### ISSUE TITLE
Documentar os pré-requisitos para desenvolvimento

### ISSUE THREAD

**Issue by lucashdp** [smart-campus-newton/me-empresta-api#6]
O que o desenvolvedor precisa instalar para começar a desenvolver ?

**Comment by RonildoSouza** [comment]
Talvez seja interessante criar um Wiki no github de Guide Development para solucionar está issue e a #7 para não adicionar muita informação do README.

Ai no README adiciona um link para o Wiki

**Comment by RonildoSouza** [comment]
Dá para criar uma pasta doc é criar varios arquivos .md igual fizeram neste projeto aqui: [Monolog - Logging for PHP](https://github.com/Seldaek/monolog)

**Comment by lucashdp** [comment]
Boa @RonildoSouza !
Eu já fiz uma documentação parecida:
https://github.com/lucashdp/catalog-microservice

**Comment by lucashdp** [comment]
Eu fiz a primeira versão no README mesmo, depois se for o caso a gente refatora !
